version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.0.2
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /home/core/volumes/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:4.3.2
    ports:
      - "3000:3000"
    links:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:1.3.3
    ports:
      - "57000:57000"
    network_mode: "host"
    volumes:
      - /etc/telegraf/telegraf.conf:/home/core/conf/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
